### ISSUE TITLE
Task 5 (DataBase Design)

### ISSUE THREAD

**Issue by ThomasGraceman** [GavinRuff007/Job-agency#4]
Task 5 (DataBase Design)
-After defining your use cases and actors and design patterns, use UML or ERD (optional) to
illustrate your DataBase (you can use draw.io, rational rose, dbdiagram.io, QuickDBD …)
-Choose a Relational database management system (MySQL, SQL-lite, PostgreSQL, Redis,
etc) for your project and explain why did you choose it (Both SQL and NoSQL databases are
allowed)

**Comment by GavinRuff007** [comment]
![_job recommendation system web-application](https://github.com/GavinRuff007/Job-agency/assets/134914088/3482d993-eaa0-4070-a91d-e92573f77138)

**Comment by GavinRuff007** [comment]
I Commited all of Task 5

**Comment by ThomasGraceman** [comment]
i added extra uml
